### ISSUE TITLE
Help/Docs link is broken

### ISSUE THREAD

**Issue by bfallik** [docker/hub-beta-feedback#248] opened 2015-08-12 01:02 UTC
When i click on Help -> Docs I see:
```
403 Forbidden

Code: AccessDenied
Message: Access Denied
RequestId: FF91CD83E776FB11
HostId: +dgEkv3/rJ94PJCBh0Y8mGdn8DdJjued2fkpIlcghHeAnZRBzrCGDdqlhOXBj8LbJ79CArD3Yxs=
An Error Occurred While Attempting to Retrieve a Custom Error Document

Code: AccessDenied
Message: Access Denied
```

The URL is http://docker-manthony.s3-website-us-east-1.amazonaws.com/.

**Comment by ChristopherBiscardi** [comment] 2015-08-12 04:49
closing as dupe of #205

**Closed by ChristopherBiscardi** 2015-08-12 04:49 UTC
