### ISSUE TITLE
Two different emails after requesting password reset

### ISSUE THREAD

**Issue by inexxt** [docker/hub-beta-feedback#226] opened 2015-08-10 04:35 UTC
After my forgotten password reset request, system sent me two emails with two different links to follow. 

First message
>You're receiving this email because someone requested a password reset for your user account at DockerHub. Please go to the following page and choose a new password: https://hub.docker.com/account/password-reset-confirm/firstLink Your username, in case you've forgotten: myUsername Thanks for using our site! The DockerHub team

Second message
>You're receiving this email because someone requested a password reset for your user account at hub.docker.com.
>
>Please go to the following page and choose a new password:
>
>https://hub.docker.com/account/password-reset-confirm/secondLink
>
>Your username, in case you've forgotten: myUsername
>
>Thanks for using our site!
>
>The hub.docker.com team

**Comment by ChristopherBiscardi** [comment] 2015-08-10 13:44
@inexxt thanks for reporting.

I was unable to reproduce this (having received only the first of the two examples)

* Did both emails arrive immediately?
* Is this easily reproducible for you? (ie: if you submit the reset-password form, does the same behavior occur?)

**Comment by inexxt** [comment] 2015-08-12 10:35
Yes, I've reproduced that. It appears the second email is sent after you succesfuly change the password using the first one.

**Comment by nhsiehgit** [comment] 2015-08-24 17:29
I've reproduced this.

We need to update the second email to be a notice that your password has changed, rather than another 'reset your password' email

**Comment by ChristopherBiscardi** [comment] 2015-08-26 05:02
thanks @nhsiehgit I've assigned you on this ticket.

**Comment by nhsiehgit** [comment] 2015-09-11 18:55
Closing as this should now be fixed!

**Closed by nhsiehgit** 2015-09-11 18:55 UTC
