### ISSUE TITLE
Invalid Page number(NAN)

### ISSUE THREAD

**Issue by satyabratachowdhury** [docker/hub-beta-feedback#61] opened 2015-06-16 04:09 UTC
Invalid page number while listing  the private repositories.

![docker](https://cloud.githubusercontent.com/assets/8176792/8175679/70304690-140b-11e5-838f-47240dc9836d.PNG)

**Comment by rrarunan** [comment] 2015-06-16 18:55
Duplicate of #36 Pagination. Thanks for the report!

**Closed by rrarunan** 2015-06-16 18:55 UTC
Labels: duplicate
