### ISSUE TITLE
Can't activate build triggers on an Automated Build.

### ISSUE THREAD

**Issue by jrhouston** [docker/hub-beta-feedback#279] opened 2015-08-14 08:38 UTC
When I click the 'activate' button under build triggers for any of my Automated Builds nothing happens. DevTools shows that the URI it's hitting is a 404:

```
PATCH https://hub.docker.com/v2/repositories/myorg/myproject/buildtrigger/ 404 (NOT FOUND)
```

**Comment by rtxm** [comment] 2015-08-14 12:01
Same as #229

**Comment by pandrew** [comment] 2015-08-15 18:52
I cant seem to activate the build triggers on the hub when the dockerfile is in a subdirectory using automated build. For example i have a repo called dockerfiles with subdirectories for each app and activating build triggers seem to have no effect. If the dockerfile is in the root of the folder there seem to be no issues.

**Comment by alunduil** [comment] 2015-08-15 19:58
+1

**Comment by ChristopherBiscardi** [comment] 2015-08-16 21:02
Closing as dupe of #229

**Closed by ChristopherBiscardi** 2015-08-16 21:02 UTC
