### ISSUE TITLE
Unable to bring up menu on iPhone

### ISSUE THREAD

**Issue by mbentley** [docker/hub-beta-feedback#212] opened 2015-08-08 09:30 UTC
When attempting to troubleshoot a failed build, I was unable to do anything with the menu in the upper right using my iPhone with safari. I don't receive any feedback that it is trying to do anything. I did get a basic auth password prompt which I commented on in another issue where someone else had the same.

This seems to be the case on any Hub page I visit.  I can't touch moby dock either to take me home.  I just seem stuck.

**Comment by john156** [comment] 2015-08-08 10:23
:+1:

**Comment by francois2metz** [comment] 2015-08-11 14:34
Duplicate of #120

**Comment by ChristopherBiscardi** [comment] 2015-08-11 18:26
Closing as dupe of #120

**Closed by ChristopherBiscardi** 2015-08-11 18:26 UTC
