### ISSUE TITLE
Not able to pull

### ISSUE THREAD

**Issue by jvassev** [docker/hub-beta-feedback#298] opened 2015-08-19 11:24 UTC
For the last week hub.docker.com is broken and cannot be accessed - all requests result in error 500:
curl registry-1.docker.io -v -L
* Rebuilt URL to: registry-1.docker.io/
* Hostname was NOT found in DNS cache
*   Trying 54.208.162.63...
* Connected to registry-1.docker.io (54.208.162.63) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: registry-1.docker.io
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 500 Server Error
< Cache-Control: no-cache
< Connection: close
< Content-Type: text/html
< 

docker.com is accessible but hub.docker.com and registry-1.docker.io are not.
<html><body><h1>500 Server Error</h1>
An internal server error occured.
</body></html>

* Closing connection 0

**Comment by jvassev** [comment] 2015-08-19 11:25
Fixing the output of curl
```
 curl registry-1.docker.io -v -L
* Rebuilt URL to: registry-1.docker.io/
* Hostname was NOT found in DNS cache
*   Trying 54.208.162.63...
* Connected to registry-1.docker.io (54.208.162.63) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: registry-1.docker.io
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 500 Server Error
< Cache-Control: no-cache
< Connection: close
< Content-Type: text/html
< 
<html><body><h1>500 Server Error</h1>
An internal server error occured.
</body></html>

* Closing connection 0
```

**Comment by ChristopherBiscardi** [comment] 2015-08-19 16:32
@jvassev what version of docker are you using?

**Comment by jvassev** [comment] 2015-08-19 17:13
I'm using 1.7.1 and 1.8.0. I have no problem pulling and even curl-ing the hub from home. However when I try accessing it over my corporate network I get error 500. That's the same output I get from "docker  pull" (no http proxy involved).
I am suspecting some intermediary causes this, it's neither docker nor the hub itself.

**Comment by ChristopherBiscardi** [comment] 2015-08-26 04:52
Closing this since it seems network related. If you feel this is a docker engine issue, please file at docker/docker.

**Comment by jvassev** [comment] 2015-08-26 17:45
It's definitely not a docker issue as I am able to pull from my laptop from different networks. An error 500 however cannot be returned by a misconfigured router or sth like that, most probably its a bad vhost configuration somewhere. If that's the problem where should I re-file this?

**Comment by ChristopherBiscardi** [comment] 2015-08-26 18:52
ok, re-opening since this hasn't been definitively closed.

**Comment by kencochrane** [comment] 2015-08-26 18:56
@jvassev if you run a dig, ping, curl from the place that works and doesn't work do you get the same IP addresses? I wonder if you have a stale DNS record somewhere and it is sending you to a server that isn't ours. If you can run it again, and let me know the IP's I'll check to see if any of those are ours.

**Comment by jvassev** [comment] 2015-08-27 09:00
Hi @kencochrane, I'm attaching dump of curl and dig
```
curl -v https://hub.docker.com
* Rebuilt URL to: https://hub.docker.com/
* Hostname was NOT found in DNS cache
*   Trying 54.172.119.237...
* Connected to hub.docker.com (54.172.119.237) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: OU=GT68254618; OU=See www.rapidssl.com/resources/cps (c)13; OU=Domain Control Validated - RapidSSL(R); CN=*.docker.com
* 	 start date: 2014-10-29 21:14:42 GMT
* 	 expire date: 2017-11-13 14:19:33 GMT
* 	 subjectAltName: hub.docker.com matched
* 	 issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA - G3
* 	 SSL certificate verify ok.
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: hub.docker.com
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 500 Server Error
< Cache-Control: no-cache
< Connection: close
< Content-Type: text/html
< 
<html><body><h1>500 Server Error</h1>
An internal server error occured.
</body></html>

* SSLv3, TLS alert, Client hello (1):
* Closing connection 0
* SSLv3, TLS alert, Client hello (1):
```

```
dig hub.docker.com

; <<>> DiG 9.9.5-9ubuntu0.2-Ubuntu <<>> hub.docker.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61071
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 4, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;hub.docker.com.			IN	A

;; ANSWER SECTION:
hub.docker.com.		240	IN	CNAME	elb-default.us-east-1.aws.dckr.io.
elb-default.us-east-1.aws.dckr.io. 762 IN CNAME	us-east-1-elbdefau-1nlhaqqbnj2z8-140214243.us-east-1.elb.amazonaws.com.
us-east-1-elbdefau-1nlhaqqbnj2z8-140214243.us-east-1.elb.amazonaws.com.	60 IN A	54.172.119.237
us-east-1-elbdefau-1nlhaqqbnj2z8-140214243.us-east-1.elb.amazonaws.com.	60 IN A	107.23.3.243
us-east-1-elbdefau-1nlhaqqbnj2z8-140214243.us-east-1.elb.amazonaws.com.	60 IN A	54.164.216.47

;; AUTHORITY SECTION:
us-east-1.elb.amazonaws.com. 206 IN	NS	ns-1119.awsdns-11.org.
us-east-1.elb.amazonaws.com. 206 IN	NS	ns-1793.awsdns-32.co.uk.
us-east-1.elb.amazonaws.com. 206 IN	NS	ns-934.awsdns-52.net.
us-east-1.elb.amazonaws.com. 206 IN	NS	ns-235.awsdns-29.com.

;; ADDITIONAL SECTION:
ns-235.awsdns-29.com.	5485	IN	A	205.251.192.235

;; Query time: 205 msec
;; SERVER: 10.23.1.1#53(10.23.1.1)
;; WHEN: Thu Aug 27 11:58:19 EEST 2015
;; MSG SIZE  rcvd: 372

```

**Comment by kencochrane** [comment] 2015-08-27 13:46
@jvassev thanks for sending that over, your dig results look good, I get the same when I run locally. 

I can't reproduce the curl command, it works for me. I have an older version of curl, 7.30.0 but that shouldn't matter.

do you get the same error when you use wget, links, lynx, or any other text or web based browser? 

You said you are not behind a proxy, so not sure what else it could be besides a bad response from our server, but not sure what might be causing it.

could you send me the results of a traceroute? 

Also can you try the curl again, but this time with a custom header and I can see if we are getting the response on the load balancers at all.

```
curl -v --header "X-HUB-TEST-HEADER: jvassev" https://hub.docker.com
```

When you run the command, let me know roughly when you ran it so I know when to look in the logs for it.

**Comment by jvassev** [comment] 2015-08-27 15:09
Here is the curl with date -R:
```
date -R && curl -v --header "X-HUB-TEST-HEADER: jvassev" https://hub.docker.com
Thu, 27 Aug 2015 11:06:38 -0400
* Rebuilt URL to: https://hub.docker.com/
* Hostname was NOT found in DNS cache
*   Trying 54.164.216.47...
* Connected to hub.docker.com (54.164.216.47) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: OU=GT68254618; OU=See www.rapidssl.com/resources/cps (c)13; OU=Domain Control Validated - RapidSSL(R); CN=*.docker.com
* 	 start date: 2014-10-29 21:14:42 GMT
* 	 expire date: 2017-11-13 14:19:33 GMT
* 	 subjectAltName: hub.docker.com matched
* 	 issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA - G3
* 	 SSL certificate verify ok.
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: hub.docker.com
> Accept: */*
> X-HUB-TEST-HEADER: jvassev
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 500 Server Error
< Cache-Control: no-cache
< Connection: close
< Content-Type: text/html
< 
<html><body><h1>500 Server Error</h1>
An internal server error occured.
</body></html>

* SSLv3, TLS alert, Client hello (1):
* Closing connection 0
* SSLv3, TLS alert, Client hello (1):

```

And the traceroute:
```
traceroute hub.docker.com 
traceroute to hub.docker.com (54.164.216.47), 30 hops max, 60 byte packets
 1  10.23.39.253 (10.23.39.253)  5.177 ms  5.143 ms  5.122 ms
 2  10.23.61.177 (10.23.61.177)  0.500 ms  0.501 ms  0.473 ms
 3  10.23.61.254 (10.23.61.254)  0.430 ms  0.452 ms  0.515 ms
 4  10.23.109.204 (10.23.109.204)  1.537 ms  1.521 ms  1.487 ms
 5  85.91.140.125 (85.91.140.125)  3.167 ms  3.145 ms  3.128 ms
 6  195.34.107.89 (195.34.107.89)  3.094 ms  2.955 ms  2.927 ms
 7  xe-10-0-0.bar1.Sofia1.Level3.net (212.162.31.13)  2.878 ms  2.793 ms  2.722 ms
 8  ae-3-80.edge2.Washington1.Level3.net (4.69.149.142)  131.439 ms  130.352 ms  130.379 ms
 9  * * *
10  AMAZON.COM.edge2.Washington1.Level3.net (4.79.22.86)  130.859 ms  130.851 ms AMAZON.COM.edge2.Washington1.Level3.net (4.79.22.74)  131.041 ms
11  * * *
12  * * *
13  205.251.245.226 (205.251.245.226)  132.140 ms  133.115 ms 205.251.245.232 (205.251.245.232)  132.861 ms
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

```

**Comment by jvassev** [comment] 2015-08-27 17:48
If it'a clue, none of get.docker.com, hub.docker.com, registry-1.docker.io works.

**Comment by kencochrane** [comment] 2015-08-27 18:06
@jvassev  thanks.

@avinson @xbglowx any ideas?

**Comment by boyanbonev** [comment] 2015-08-27 18:32
Hi,
I have to report the same issue as jvassev. I see the same symptoms as he does.

**Comment by kencochrane** [comment] 2015-08-27 19:32
@jvassev @boyanbonev  what is the IP address you are connecting from?

**Comment by jvassev** [comment] 2015-08-27 20:14
http://www.whatismypublicip.com/ reports 85.91.140.124

**Comment by xbglowx** [comment] 2015-08-27 21:13
@jvassev your IP was in our blacklist. I removed it. Please try again and let me know if things are working now.

**Comment by jvassev** [comment] 2015-08-27 21:20
Everything is working now :)
Thanks, closing this issue.

**Closed** 2015-08-27 21:20 UTC
