### ISSUE TITLE
Trying to activate build triggers

### ISSUE THREAD

**Issue by bastianwegge** [docker/hub-beta-feedback#229] opened 2015-08-10 12:36 UTC
Hey guys,

I'm trying to activate build triggers for the only private project in my docker-hub account. I'm getting a 404 back from the `client.78f7642e1d6b566ac84b.js:50PATCH`.

Any ideas?

**Comment by ChristopherBiscardi** [comment] 2015-08-10 13:29
Thanks for reporting :)

I've repro'd the same response for PUTs and PATCHs. In the meantime, there is the "Trigger a Build" button, which will fire a request to rebuild the repo.

@nhsiehgit Is this an issue with the build trigger API?

```
/v2/repositories/:namespace/:name/buildtrigger/
```

**Comment by bastianwegge** [comment] 2015-08-10 13:32
Thanks for the quick reply, I'm trying to automate our build process. Seem's like I have to exclude the docker-hub for now :(. Is there any way to curl the buildtrigger?

**Comment by ChristopherBiscardi** [comment] 2015-08-10 14:02
> Is there any way to curl the buildtrigger?

For activating the trigger (ie: generating a token), it would be the same endpoints we are using the new UI. So if there is a problem in those endpoints (which there seems to be), then no.

support@docker.com may be able to generate one for you though.

**Comment by godfriedmeesters** [comment] 2015-08-13 08:23
Still experiencing the same problem

**Comment by rtxm** [comment] 2015-08-14 11:59
When we click on the "Activate button" the browser's debugger says:

    Request URL:https://hub.docker.com/v2/repositories/:namespace/:name/buildtrigger/
    Request Method:GET
    Status Code:404 NOT FOUND

**Comment by ChristopherBiscardi** [comment] 2015-08-19 16:31
I've confirmed that build triggers are fixed in prod. Please let us know if you are still experiencing an issue.

![screenshot 2015-08-19 09 30 49](https://cloud.githubusercontent.com/assets/551247/9362388/007db40a-4655-11e5-8c84-28519032adb5.png)

**Closed by ChristopherBiscardi** 2015-08-19 16:31 UTC
Labels: bug

**Comment by bastianwegge** [comment] 2015-08-19 16:33
It's working for me, thanks!

**Comment by godfriedmeesters** [comment] 2015-08-19 16:39
Thanks it's indeed ok now
