### ISSUE TITLE
Orgs added to teams create list entries with URL that always throws 404

### ISSUE THREAD

**Issue by ewindisch** [docker/hub-beta-feedback#79] opened 2015-06-16 19:42 UTC
Adding an org to a team creates a link that gives a 404:

![](http://g.recordit.co/JlsyTWg8Xs.gif)

**Comment by rrarunan** [comment] 2015-06-16 23:48
So, `/u/<org>` is the correct URL, but there is an issue with how we handle organization profiles at the moment. We will consider it this bug, where we get a 404 on organization profile pages and fix this.

**Comment by rrarunan** [comment] 2015-06-19 05:23
I'm closing this as a duplicate of #45 .

**Closed by rrarunan** 2015-06-19 05:23 UTC
Labels: bug, duplicate
