### ISSUE TITLE
Can't configure Bitbucket automated builds

### ISSUE THREAD

**Issue by philp** [docker/hub-beta-feedback#283] opened 2015-08-15 10:33 UTC
Trying to connect Bitbucket through the Docker Hub UI, but the option to link to Bitbucket does nothing.

**Comment by markosamuli** [comment] 2015-08-18 20:14
@philp does it look similar to the issue I had? See #213

**Comment by philp** [comment] 2015-08-18 20:39
@markosamuli No, I can't even get to the point of creating an automated build. The UI won't let me even start the process of connecting my Bitbucket account — clicking on the link does absolutely nothing. Very frustrating.

**Comment by rrarunan** [comment] 2015-08-18 21:05
@philp Can you please let us know if you see a popup being blocked by any chance, when you try to link to bitbucket? What browser and OS are you using?

**Comment by philp** [comment] 2015-08-18 21:10
@rrarunan Ah-ha — looks like that's what it was. I was trying this in Safari on OS X and it wasn't giving me any kind of indication that a popup was being blocked. Just tried in Chrome, and there was a notification about a blocked popup to Bitbucket. Granted permission, and it allowed me to get to connect accounts.

Thanks.

**Comment by rrarunan** [comment] 2015-08-18 21:14
@philp Glad it works! And sorry about the delay in the response. Closing this one.

**Closed by rrarunan** 2015-08-18 21:14 UTC

**Comment by joshuataylor** [comment] 2015-12-15 05:30
In Chrome, clicking Link Bitbucket opens a new tab, then redirects back to https://hub.docker.com/account/authorized-services/

**Comment by rrarunan** [comment] 2015-12-15 05:37
@joshuataylor TIA. Can you please try this in `incognito mode` and report the result? Also, let us know if you haven't already linked this bitbucket account to another hub account.

**Comment by kirinse** [comment] 2016-08-02 06:17
@rrarunan i have met same issue with @joshuataylor, even in incognito mode.

**Comment by bcwalrus** [comment] 2016-08-05 20:19
@joshuataylor @kirinse I can occasionally reproduce this. A workaround for me: in the new window that it opens (the one that looks like the same window), click on "Bitbucket" again. Hope that unblocks you.
