### ISSUE TITLE
Build Details page not rendering latest history. Client Error

### ISSUE THREAD

**Issue by Jeff-Lewis** [docker/hub-beta-feedback#247] opened 2015-08-12 00:38 UTC
##### Environment:
- Latest Chrome 44.0.2403.130 m
- No Chrome Extensions (empty Profile)
- Win7

##### Steps to reproduce
1) Login to personal account.
2) Switch to Organization's Repo's
3) Click Repo that is a automated build
4) Click Build Details

##### Symptom:
The build history grid is missing paging or any way to see latest builds. 

![image](https://cloud.githubusercontent.com/assets/676289/9214070/5a2673d2-4067-11e5-92d2-005a80f815d8.png)

##### Browser console warnings:
Warning: Failed propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `RepositoryDetails`.

Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of BuildDetails. See https://fb.me/react-warning-keys for more information.

##### Firefox
Also, in latest Firefox v40.0, same steps produce the same console warnings.
Although, in Firefox, the console is also reporting the follow on many ajax requests.

20:35:53.165 The site specified an invalid Strict-Transport-Security header.1 buildhistory

**Comment by ChristopherBiscardi** [comment] 2015-08-12 04:41
@Jeff-Lewis thanks for reporting this.

There definitely needs to be more builds on this page so we'll bump the page_size at least.

I am unable to reproduce the missing build though. All my attempts have resulted in a view of the latest pending build for users and orgs.

* What is the org name in the screenshot? (feel free to send this to support@docker.com if you intentionally aren't showing it in this screenshot)
* Have you pushed since 7/24? (ie: are there multiple builds missing or just the most recent?)

**Comment by Jeff-Lewis** [comment] 2015-08-12 05:30
Thanks for getting back. Yes, there have been dozens of build after this and I also before. I'm not sure why it's only showing those dates. In the screenshot it states "Last pushed 13 minutes ago."
I'll send a request into support. Thanks.

**Comment by camallen** [comment] 2015-08-12 10:46
I'm seeing the same behaviour of not reporting the latest builds, last pushed 13 hours ago but list shows builds from July 23rd back.

![image](https://cloud.githubusercontent.com/assets/295329/9222206/b6ae1c92-40e7-11e5-9831-183fc2993c96.png)

**Comment by kencochrane** [comment] 2015-08-12 17:06
I was able to confirm this is an issue and track the problem back to the API result. For some reason the first page of API results for the build details are not in the correct order. We will have to update the API endpoint to enforce the correct ordering.. 

The UI shouldn't have to change, besides maybe adding pagination. Once the API is fixed, the page results should be in the correct order.

/cc @fxdgear @ChristopherBiscardi

**Comment by kencochrane** [comment] 2015-08-13 11:03
@Jeff-Lewis @camallen this should be fixed, please confirm

**Comment by camallen** [comment] 2015-08-13 13:52
@kencochrane looks good to me, latest builds show up first in the list.

**Comment by Jeff-Lewis** [comment] 2015-08-13 14:12
@kencochrane Yes, thank you. Will we be able to see full history at some point? (paging)

**Comment by nhsiehgit** [comment] 2015-08-20 22:33
closing since this looks like it's been resolved.

Yes paging should be a ticket item. if it's not feel free to create a new issue!

**Closed by nhsiehgit** 2015-08-20 22:33 UTC
Labels: bug
