### ISSUE TITLE
Pagination navbar is not intuitive

### ISSUE THREAD

**Issue by albertinisg** [docker/hub-beta-feedback#240] opened 2015-08-11 10:19 UTC
Everytime I open my dashboard, the pagination navbar just displays `1` even if I have more than 1 page there. That makes me think that my other docker images are not available there.

However is not a bug, the pagination component should be redesigned as it is a bit confusing right now.

**Comment by dickensian** [comment] 2015-08-11 10:33
Agreed, pagination needs to show the total number of pages or at the very least have some way of indicating that there are more pages in a given direction.

**Comment by francois2metz** [comment] 2015-08-11 14:36
Almost duplicate of #36.

**Comment by nhsiehgit** [comment] 2015-08-11 15:53
Thanks all, we have a fix in pending deploy!

**Comment by rrarunan** [comment] 2015-08-11 18:01
We have updated the pagination component. @albertinisg @dickensian @francois2metz Let us know what you think.

**Comment by francois2metz** [comment] 2015-08-11 18:20
Woooooot. Awesome. :tada:

**Comment by rrarunan** [comment] 2015-08-11 18:24
Closing.

**Closed by rrarunan** 2015-08-11 18:24 UTC
Labels: pending-deploy

**Comment by albertinisg** [comment] 2015-08-11 18:56
Looks exactly how I was thinking @rrarunan :smile:  Thanks for the quick fix!

**Comment by rrarunan** [comment] 2015-08-11 18:57
@albertinisg thanks to @ChristopherBiscardi too. Thanks for the report.
