### ISSUE TITLE
Account Settings -> New Email -> Confirmation

### ISSUE THREAD

**Issue by noxsnono** [docker/hub-beta-feedback#94] opened 2015-06-19 11:29 UTC
Hi

Adding 2 news email, i never receive emails to confirm them

**Comment by kizbitz** [comment] 2015-08-18 16:49
Could be merged with: https://github.com/docker/hub-beta-feedback/issues/17

**Comment by rrarunan** [comment] 2015-08-18 21:34
Closing as dupe of #17

**Closed by rrarunan** 2015-08-18 21:34 UTC
Labels: bug
