### ISSUE TITLE
Tags URL for repos returns 502 bad gateway

### ISSUE THREAD

**Issue by tonyhb** [docker/hub-beta-feedback#89] opened 2015-06-18 23:54 UTC
Refreshing on the Tags URL causes a bad gateway:

URL structure:  `https://hub-beta.docker.com/r/:org/:repo/tags/`

**Comment by ChristopherBiscardi** [comment] 2015-06-19 03:28
closing as dupe of #90

**Closed by ChristopherBiscardi** 2015-06-19 03:28 UTC
