### ISSUE TITLE
Pagination UI issue - displaying NaN

### ISSUE THREAD

**Issue by heddle317** [docker/hub-beta-feedback#70] opened 2015-06-16 17:44 UTC
I'm using Google chrome, and the pagination for a single page displays the next page as "NaN". I've attached a screenshot.
![dockerhub_nan_bug](https://cloud.githubusercontent.com/assets/525136/8189962/930d1b80-1414-11e5-965e-b6b4c01414c8.png)

**Comment by ewindisch** [comment] 2015-06-16 18:49
Same here. Refreshing, I ended up getting "1" and "3" as page numbers (without a 2). Clicking neither the  NaN nor 3 worked.

**Comment by rrarunan** [comment] 2015-06-16 18:54
Duplicate of #36 Pagination support. This is slated for a fix this week. Thanks for the report!

**Closed by rrarunan** 2015-06-16 18:54 UTC
Labels: duplicate
