### ISSUE TITLE
Gravatar background color

### ISSUE THREAD

**Issue by ruffsl** [docker/hub-beta-feedback#210] opened 2015-08-07 21:49 UTC
Shouldn't the default Gravatar background color be white? I think for profile images this is de facto standard. Perhaps I'm wrong, but I think the neon blue makes most logos look a little silly.

## Information
* Operating system: Ubuntu 14.04 LTS
* Browser and Browser version: Firefox Version 39.0 (64-bit)
* URL for the page in question
 * https://hub-beta.docker.com/u/osrf/
* Screenshots of the issue (if applicable)
![image](https://cloud.githubusercontent.com/assets/2293573/9146625/0f9279b2-3d13-11e5-8a69-a22eb4e08099.png)
* Any error messages (on screen or in browser console)
```
The site specified an invalid Strict-Transport-Security header.[Learn More] osrf
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] forms2.min.js
The site specified an invalid Strict-Transport-Security header.[Learn More] font-awesome.min.css
The site specified an invalid Strict-Transport-Security header.[Learn More] main-0-2c72789e1d2c88d5e145.css
The site specified an invalid Strict-Transport-Security header.[Learn More] main.css
The site specified an invalid Strict-Transport-Security header.[Learn More] client.2c72789e1d2c88d5e145.js
The site specified an invalid Strict-Transport-Security header.[Learn More] mini-logo.svg
The site specified an invalid Strict-Transport-Security header.[Learn More] avatar
Security wrapper denied access to property _gaUserPrefs on privileged Javascript object. Support for exposing privileged objects to untrusted content via __exposedProps__ is being gradually removed - use WebIDL bindings or Components.utils.cloneInto instead. Note that only the first denied property access from a given global object will be reported. analytics.js:4:0
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create client.2c72789e1d2c88d5e145.js:19:29971
"Warning: Failed propType: Required prop `next` was not specified in `Pagination`. Check the render method of `t`." client.2c72789e1d2c88d5e145.js:1:15690
"Warning: Failed propType: Required prop `prev` was not specified in `Pagination`. Check the render method of `t`." client.2c72789e1d2c88d5e145.js:1:15690
The site specified an invalid Strict-Transport-Security header.[Learn More]
```
* The rough date and time the error occurred (be sure to include your time zone)
 * 2:44 PM Wednesday, August 7, 2015 (PDT)

**Comment by ChristopherBiscardi** [comment] 2015-08-07 21:51
Closing as dupe of #192

**Comment by ruffsl** [comment] 2015-08-07 21:52
Woops, thanks @ChristopherBiscardi

**Closed by ChristopherBiscardi** 2015-08-07 21:51 UTC
